version: '3'
services:
  mysql:
    image: mysql:oraclelinux9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: e-commerce-app
    ports:
      - "3306:3306"

  app:
    image: duydl12/e-commerce-api-app:latest
    depends_on:
      - mysql
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/e-commerce-app?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
