[build]
builder = "NIXPACKS"

[deploy]
startCommand = "./mvnw spring-boot:run -DskipTests"
healthcheckPath = "/health"
healthcheckTimeout = 200
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[env]
JAVA_OPTS = "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75 -Dspring.profiles.active=prod"
PORT = "8080"
